---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cnu2018-dev
  name: asingla-ass01b-servervol-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: px-standard
