---
apiVersion: v1
kind: Pod
metadata:
  namespace: cnu2018-dev
  name: asingla-ass01b-server-container 
spec:
  containers:
    - name: asingla-ass01b-server-container
      image: registry2.swarm.devfactory.com/cnu-ass01b-server
      env:
      - name: PORT
        value: "9999"
      volumeMounts:
        - name: servervol
          mountPath: /serverdata
  volumes:
    - name: servervol
      persistentVolumeClaim:
        claimName: asingla-ass01b-servervol-claim
