package com.cnu.assignment04.controllers;

import com.cnu.assignment04.entities.Restaurant;
import com.cnu.assignment04.repositories.RestaurantRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;


@Controller
@RequestMapping(path="/restaurants")
public class RestaurantController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private RestaurantRepository restaurantRepository;

    @GetMapping(path="/")
    public @ResponseBody Iterable<Restaurant> getAllRestaurants() {
        Pageable limit = PageRequest.of(0,10);

        // This returns a JSON or XML with the users
        return restaurantRepository.getNRestaurants(1, limit);
    }
}