# Generated by Django 2.1 on 2018-08-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweggy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisine',
            name='business_count',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='neighbourhood',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='state',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, default='up', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=1.1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=2.2, max_digits=11),
            preserve_default=False,
        ),
    ]
