# Generated by Django 2.1 on 2018-08-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweggy', '0002_auto_20180815_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='is_open',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(),
        ),
    ]
