---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: cnu2018-dev
  name: asingla-ass01b-cronjob 
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cnu2018
          containers:
            - name: asingla-ass01b-client-container
              image: registry2.swarm.devfactory.com/asingla-cnu-ass01b-client
              env:
              - name: PORT
                value: "9999"
              - name: SERVER_HOSTNAME
                value: "10.111.213.154"
              args:
              - /bin/sh
              - ./client.sh
          restartPolicy: OnFailure