# Generated by Django 2.1 on 2018-08-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swaggy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
