# Generated by Django 2.1 on 2018-08-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaggy', '0002_auto_20180813_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(),
        ),
    ]
