# Generated by Django 2.1 on 2018-08-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaggy', '0003_auto_20180813_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='business_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='stars',
            field=models.FloatField(default=0),
        ),
    ]
